language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

branches:
  except:
    - gh-pages

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - php bin/codecept run  # self tests
