language: php

php:
  - '5.5'
  - '5.6'

branches:
  except:
    - gh-pages

services:
  - mysql
  -

cache:
  directories:
    - $HOME/.composer/cache
    - bin
    - vendor

before_install:
  mysql  -e "CREATE DATABASE old06; use old06; source dump.sql; show databases;";


install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - php bin/codecept run  # self tests
