language: php

php:
  - '5.5'
  - '5.6'

branches:
  except:
    - gh-pages

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - bin
    - vendor

before_install:
  mysql -e "CREATE DATABASE IF NOT EXISTS test; use test; source dump.sql; show tables;";


install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bin/phantomjs --webdriver=4444 > /dev/null 2>&1 & #start phantomjs
  - php bin/codecept build  # self tests
  - php bin/codecept run  # self tests
